/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: (typeof import('@lucaswerey/dslib-pfe'))['Avatar']
    BulletPoints: (typeof import('@lucaswerey/dslib-pfe'))['BulletPoints']
    Button: (typeof import('@lucaswerey/dslib-pfe'))['Button']
    HelloWorld: (typeof import('./components/HelloWorld.vue'))['default']
    IconCommunity: (typeof import('./components/icons/IconCommunity.vue'))['default']
    IconDocumentation: (typeof import('./components/icons/IconDocumentation.vue'))['default']
    IconEcosystem: (typeof import('./components/icons/IconEcosystem.vue'))['default']
    IconsBase: (typeof import('@lucaswerey/dslib-pfe'))['IconsBase']
    IconSupport: (typeof import('./components/icons/IconSupport.vue'))['default']
    IconTooling: (typeof import('./components/icons/IconTooling.vue'))['default']
    InputField: (typeof import('@lucaswerey/dslib-pfe'))['InputField']
    Loader: (typeof import('@lucaswerey/dslib-pfe'))['Loader']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SnackBar: (typeof import('@lucaswerey/dslib-pfe'))['SnackBar']
    StepIndicator: (typeof import('@lucaswerey/dslib-pfe'))['StepIndicator']
    TheWelcome: (typeof import('./components/TheWelcome.vue'))['default']
    ToggleButton: (typeof import('@lucaswerey/dslib-pfe'))['ToggleButton']
    VideoPlayer: (typeof import('@lucaswerey/dslib-pfe'))['VideoPlayer']
    WelcomeItem: (typeof import('./components/WelcomeItem.vue'))['default']
  }
}
