/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('@lucaswerey/dslib-pfe')['Avatar']
    Button: typeof import('@lucaswerey/dslib-pfe')['Button']
    CheckBox: typeof import('@lucaswerey/dslib-pfe')['CheckBox']
    ChipContainer: typeof import('@lucaswerey/dslib-pfe')['ChipContainer']
    CompatibilityInput: typeof import('./components/mySpace/recruiter/newOffer/CompatibilityInput.vue')['default']
    ContractTypeinput: typeof import('./components/mySpace/recruiter/newOffer/ContractTypeinput.vue')['default']
    DropDown: typeof import('./components/navBars/DropDown.vue')['default']
    IconsBase: typeof import('@lucaswerey/dslib-pfe')['IconsBase']
    InputField: typeof import('@lucaswerey/dslib-pfe')['InputField']
    MoreCrits: typeof import('./components/mySpace/recruiter/newOffer/MoreCrits.vue')['default']
    MyDemand: typeof import('./components/mySpace/students/MyDemand.vue')['default']
    MyMatch: typeof import('./components/mySpace/students/MyMatch.vue')['default']
    MyOffers: typeof import('./components/mySpace/recruiter/MyOffers.vue')['default']
    MyProfils: typeof import('./components/mySpace/recruiter/MyProfils.vue')['default']
    MyRefused: typeof import('./components/mySpace/students/MyRefused.vue')['default']
    NavBarCompany: typeof import('./components/navBars/NavBarCompany.vue')['default']
    NavBarStudent: typeof import('./components/navBars/NavBarStudent.vue')['default']
    NavBarWelcome: typeof import('./components/navBars/NavBarWelcome.vue')['default']
    NewOffer: typeof import('./components/mySpace/recruiter/NewOffer.vue')['default']
    NewofferHeader: typeof import('./components/mySpace/recruiter/newOffer/NewofferHeader.vue')['default']
    RankingContainer: typeof import('@lucaswerey/dslib-pfe')['RankingContainer']
    RecruiterFormStep1: typeof import('./components/signUp/recruiter/RecruiterFormStep1.vue')['default']
    RecruiterFormStep2: typeof import('./components/signUp/recruiter/RecruiterFormStep2.vue')['default']
    RecruiterSignup: typeof import('./components/signUp/RecruiterSignup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('@lucaswerey/dslib-pfe')['SelectField']
    SnackBar: typeof import('@lucaswerey/dslib-pfe')['SnackBar']
    SpaceRecruiter: typeof import('./components/mySpace/recruiter/SpaceRecruiter.vue')['default']
    SpaceStudent: typeof import('./components/mySpace/students/SpaceStudent.vue')['default']
    StepIndicator: typeof import('@lucaswerey/dslib-pfe')['StepIndicator']
    StudentFormStep1: typeof import('./components/signUp/students/StudentFormStep1.vue')['default']
    StudentFormStep2: typeof import('./components/signUp/students/StudentFormStep2.vue')['default']
    StudentFormStep3: typeof import('./components/signUp/students/StudentFormStep3.vue')['default']
    StudentSignup: typeof import('./components/signUp/StudentSignup.vue')['default']
    SubnavRecruiter: typeof import('./components/mySpace/recruiter/SubnavRecruiter.vue')['default']
    SubnavStudent: typeof import('./components/mySpace/students/SubnavStudent.vue')['default']
  }
}
