/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('@lucaswerey/dslib-pfe')['Avatar']
    Button: typeof import('@lucaswerey/dslib-pfe')['Button']
    CheckBox: typeof import('@lucaswerey/dslib-pfe')['CheckBox']
    ChipContainer: typeof import('@lucaswerey/dslib-pfe')['ChipContainer']
    IconsBase: typeof import('@lucaswerey/dslib-pfe')['IconsBase']
    InputField: typeof import('@lucaswerey/dslib-pfe')['InputField']
    NavBarCompany: typeof import('./components/navBars/NavBarCompany.vue')['default']
    NavBarStudent: typeof import('./components/navBars/NavBarStudent.vue')['default']
    NavBarWelcome: typeof import('./components/navBars/NavBarWelcome.vue')['default']
    RankingContainer: typeof import('@lucaswerey/dslib-pfe')['RankingContainer']
    Recr: typeof import('@lucaswerey/dslib-pfe')['Recr']
    RecruiterFormStep1: typeof import('./components/signUp/recruiter/RecruiterFormStep1.vue')['default']
    RecruiterFormStep2: typeof import('./components/signUp/recruiter/RecruiterFormStep2.vue')['default']
    RecruiterSignup: typeof import('./components/signUp/RecruiterSignup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectField: typeof import('@lucaswerey/dslib-pfe')['SelectField']
    SnackBar: typeof import('@lucaswerey/dslib-pfe')['SnackBar']
    StepIndicator: typeof import('@lucaswerey/dslib-pfe')['StepIndicator']
    StudentFormStep1: typeof import('./components/signUp/students/StudentFormStep1.vue')['default']
    StudentFormStep2: typeof import('./components/signUp/students/StudentFormStep2.vue')['default']
    StudentFormStep3: typeof import('./components/signUp/students/StudentFormStep3.vue')['default']
    StudentSignup: typeof import('./components/signUp/StudentSignup.vue')['default']
  }
}
